image: ubuntu:xenial
.job_name:
  script: &build_script
    - apt-get update -qyy
    - apt-get install -qyy curl bc make git build-essential
    - apt-get --yes install libglib2.0-dev curl flex g++-multilib gcc-multilib gnupg gperf lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libwxgtk-media3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev
    - git clone https://github.com/assusdan/arm-cortex-linux-gnueabi-linaro_5.2
    - export KBUILD_BUILD_USER=sunk851 #это правите по вкусу, можно вписать ник
    - export KBUILD_BUILD_HOST=4pda
    - export PATH=$PATH:$PWD/arm-cortex-linux-gnueabi-linaro_5.2/bin/ 
    - export ARCH=arm
    - export SUBARCH=arm
    - export CROSS_COMPILE=$PWD/arm-cortex-linux-gnueabi-linaro_5.2/bin/arm-cortex-linux-gnueabi-
    - make X5PRO_6735m_defconfig
    - make
    - curl --upload-file arch/arm/boot/Image.gz-dtb https://transfer.sh/Image.gz-dtb |grep transfer
job_name:
  stage: 8
  tags:
    - gitlab-org
  script: *build_script