image: ubuntu:xenial
.x5pro_8.0:
 before_script: &build_script
    - apt-get update -qyy
    - apt-get --yes install -qyy curl bc make git build-essential libglib2.0-dev curl flex g++-multilib gcc-multilib gnupg gperf lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libwxgtk-media3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev
    - export KBUILD_BUILD_USER=sunk851
    - export KBUILD_BUILD_HOST=4pda
    - git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
    - export PATH=$PATH:$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/
    - export CROSS_COMPILE=$PWD/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin/aarch64-linux-android-
    - export ARCH=arm64
    - export SUBARCH=arm64
    - make X5PRO_6735m_defconfig -j50000
    - make -j1000
    - curl --upload-file arch/arm64/boot/Image.gz-dtb https://transfer.sh/Image.gz-dtb
x5pro_8.0:
  stage: test
  tags:
    - gitlab-org
  script: *build_script
